services:
  mongodb:
    image: mongo:latest
    container_name: academic-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secureMongoRoot123
      MONGO_INITDB_DATABASE: academic_tracker
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017"
    networks:
      - academic-network
    healthcheck:
      test: ["CMD", "mongosh", "-u", "root", "-p", "secureMongoRoot123", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 30s
      retries: 3

  api:
    build: ./backend
    container_name: academic-api
    ports:
      - "3000:3000"
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./backend:/api
      - /api/node_modules
    networks:
      - academic-network

  seed:
    build: ./backend
    container_name: academic-seed
    command: npm run seed
    depends_on:
      mongodb:
        condition: service_healthy
    restart: "no"
    networks:
      - academic-network

volumes:
  mongodb_data:

networks:
  academic-network:
    driver: bridge